### ISSUE TITLE
Fix undo meta tags

### ISSUE THREAD

**Issue by ai** [logux/logux_rails#73]
[`Logux.undo()`](https://github.com/logux/logux_rails/blob/f41e761f462d539bbc8119148905b35ad4c8dc79/lib/logux.rb#L78-L83) should copy all re-send keys from origin action (`channels`, etc).

Here is JS implementation: https://github.com/logux/server/blob/master/base-server.js#L676-L682

**Comment by ai** [comment]
@dsalahutdinov this issue was reported by Amplifr users, so it is important

**Comment by dsalahutdinov** [comment]
Hey, We will fix it next week with help of @dreikanter
